version: '3.8'

services:
  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: sidharth
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: myapp_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql-network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql-container
      PMA_USER: root
      PMA_PASSWORD: sidharth
    ports:
      - "8083:80"  # Port mapping for phpMyAdmin
    networks:
      - mysql-network

  # Laravel/PHP Service
  app:
    image: php:8.2-apache
    container_name: lookin-container
    volumes:
      - ../lookin-app:/var/www/html  # Ensure this path is correct
    ports:
      - "8084:80"  # Port mapping for Laravel app
    networks:
      - mysql-network
    depends_on:
      - mysql

networks:
  mysql-network:
    external: true

volumes:
  mysql_data:
